### ISSUE TITLE
Generated router uses back slashes for permalink

### ISSUE THREAD

**Issue by Towerism** [nuxt-community/nuxtent-module#103]
I am on windows.

My generated route looks like this:
```
		{
			path: "\\posts\\:year\\:slug",
			component: _0a3eb4af,
			name: "posts-slug"
		}
```
My config looks like this:
```
  nuxtent: {
    content: [
      ['posts', {
        page: 'posts/_slug',
        permalink: 'posts/:year/:slug',
        data: {
          author: 'Martin Fracker'
        }
      }]
    ]
  },
```
This is what I get from hitting the content-api endpoint:
```
{"content-endpoints":["\\posts"]}
```
If I manually edit the router and change the backslashes to forward slashes which is what they should be in the first place, then it works.

I tried this with the starter template as well and after removing the component in the markdown file to get rid of the module build fail warning, the same back slash is observed in the generated router.js file.

**Comment by dahrens** [comment]
Looks like this one breaks in that case. It uses (`path.join`)[https://nodejs.org/api/path.html#path_path_join_paths] to manipulate the route.
