### ISSUE TITLE
Links in generated website lead to "Network Error"

### ISSUE THREAD

**Issue by dahrens** [nuxt-community/nuxtent-module#104]
I have problems to get my nuxtent based generated website to work properly. And I'm also not sure whether it is related to nuxtent or nuxtjs itself, but as I currently guess that nuxtent does some magic regarding the generation of files and links I decided to post it here at first.

Using `yarn run dev` everything works as expected. I can open the landing page and also navigate to linked writings from the content folder. When I run `yarn run generate` the dist folder also looks very promising, including all files I expect there to be.

To test the build I start a local webserver

```bash
cd dist
python -m SimpleHTTPServer 3344
```

When navigating to http://localhost:3344 contents from `page/index.vue` appear. But when I then hit a link which points to a page that should be there due to dynamic routing and in the html also correctly points to `http://localhost:3344/2017/nuxtent` I encouter an error:

![screenshot-2017-10-22 network error](https://user-images.githubusercontent.com/342831/31857252-bf48e0ac-b6d9-11e7-91f5-8dde4d661f25.png)

The error is obviously raised by the included javascript from nuxtjs, because when I navigate manually to the link, the page shows up properly.

I'm using the following library versions (based on `yarn.lock`)

* nuxtjs/axios 4.4.0 (which was installed with `lastest` in package.json)
* nuxt 1.0.0-rc9 (which was installed with `^1.0.0-rc11` in package.json - :fearful: )
* nuxtent 1.0.2 (which was installed with `lastest` in package.json)

I already digged through the nuxtjs documentation and stumpled upon [dynamic routes configuration](https://nuxtjs.org/api/configuration-generate#routes) - but configuring them does not help.

**nuxtent.config.js**

```javascript
module.exports = {
  content: [
    ['writings', {
      permalink: ':year/:slug',
      page: '/_writings',
      generate: [
        'get', 'getAll'
      ]
    }],
    ['projects', {
      permalink: ':slug',
      isPost: false,
      page: '/_projects',
      generate: [
        'get', 'getAll'
      ]
    }]
  ]
}
```

**nuxt.config.js**

```javascript
module.exports = {
  router: {
    linkActiveClass: 'is-active'
  },
  build: {
    extend (config, ctx) {
      if (ctx.isClient) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },
  modules: [
    ['nuxtent']
  ],
  loading: { color: '#c9981c' },
  generate: {
    routes: [
      '/2017/nuxtent',
      'barf'
    ]
  }
}
```

**Comment by alidcastano** [comment]
You shouldn't need to include any content routes inside `generate.routes` as nuxtent handles this for you. Removing that part might solve your problem. 

Otherwise, let me know if there's any other information printed regarding the error. Also, @medfreeman will be releasing some fixes hopefully tomorrow, in case your problem relates to any previous issues. :)

**Comment by dahrens** [comment]
Thanks for your quick reply!

Adding generate to the config was an attempt to fix the problem. The error persists without it.

I removed it again and inspected the network tab when hitting the button and found out, that it first loads a js source - in my current build called `http://localhost:3344/_nuxt/pages/_writings.b813cba1a8d2af1e9032.js` (which was already loaded before) and afterwards executes an ajax call to `http://localhost:3000/_nuxt/content/writings/2017.nuxtent.json`, which fails.

This file would be there, if the port would be correct. Which seems to cause the error.

My api settings look like that:

```javascript
api: {
  baseURL: process.env.NODE_ENV === 'production'
    ? 'https://part-of.me'
    : 'http://localhost:3000'
}
```

I would expect the generated result to just point to a static HTML file without being intercepted. In fact I'd love to see the generated result being indepentent from my production environment at all! Or is this how nuxt behaves in general?

**Comment by dahrens** [comment]
After playing with plain nuxtjs and diggin through your sources, I guess that [this is the place](https://github.com/nuxt-community/nuxtent-module/blob/master/lib/plugins/requestContent.js#L44), which your reserved to circumvent the content API in production builds? I'm curious regarding the fixes from @medfreeman !

Please let me know if contributions on that are welcome and whether I'm on the right track or not.

:+1: for the whole module - the sources are quite readable as far as I can assess this

**Comment by alidcastano** [comment]
Thank you for your interest, contributions are always welcome! 

By production builds, are you referring to static builds? Nuxtent supports both static and dynamic sites, but the line of code that you linked pertains to the content generation for static sites, which is why it is an empty return for the server. Here's the file where static content/assets are built: https://github.com/nuxt-community/nuxtent-module/blob/master/lib/content/build.js.

**Comment by alidcastano** [comment]
Also, Nuxtent only loads file via server api at `content-api` endpoint or via browserf files at `_nuxt/content`. So the call that pertains to Nuxtent is `http://localhost:3000/_nuxt/content/writings/2017.nuxtent.json`.

Is this for a dynamic or static site? 

Why are both ports - 3344 and 3000 - there? Based on your configuration, you want port 3000, which is where Nuxtent is loading the files for.

**Comment by dahrens** [comment]
The site we're talking about is dynamic.

I currently try test the static site generated by nuxtent using a local python webserver, thats the reason for the different port.

```bash
cd dist
python -m SimpleHTTPServer 3344
```

I would like the result of `yarn run generate` to be able to run on whatever port I'd like to.

But depending on my configuration and the things I thought I've understand about `baseURL` I was expecting `http://part-of.me` to be the picked URL (which should also raise the error) as I thought that `generate` builds for production.

**Comment by dahrens** [comment]
Thanks for the hint on the sources.

Do I get it right that the following code causes the hrx that queries the JSON file?

```javascript
export default {
 asyncData: async ({ app, route }) => {
    return {
      writing: await app.$content('/writings').get(route.path)
    }
  }
}
```

And that this call is executed by (in my case) **_writings.vue**, which is responsible to receive the content somehow? I was expecting this to be done on generate, so that the HTML file already includes the rendered template.

**Comment by alidcastano** [comment]
Ah okay. So from what I see, you're running the site on `3344` but you're not setting the environment variable to production, so you're pages are being fetched at `localhost:3344` by nuxt (the server you initiated) and at `3000` (the server you configured) by nuxtent. Makes sense?

The reason you need to configure the port properly is because Nuxt uses axios to fetch the content via serverMiddleware.

**Comment by dahrens** [comment]
I'm to spoiled by the vue webpack template I guess :) Thanks for your assistance.

Do you think it is worth to figure out how to get rid of the baseURL setting. I'd love to have a generated static site that is not bound to any specific webserver configuration - this is at least what I'd expect from a static site generator.

**Comment by alidcastano** [comment]
I believe  (per issue #53 / and PR #67) you can leave the `baseURL` empty and files will be fetched locally for static builds. Sorry for not specifying that early, documentation on that def needs to be updated

**Comment by alidcastano** [comment]
Try that and if it doesn't work feel free to open up a new issue

**Comment by dahrens** [comment]
Thanks a bunch! This was exactly what I was looking for and it works like a charm! :) No problem that the docs were not that clean. At least the feature is implemented and it was a good opportunity to get in touch with the sources.

**Comment by alidcastano** [comment]
Awesome! Once your site is running on Nuxtent, free to edit the README and add it to the list of sites 🥇

**Comment by alidcastano** [comment]
@dahrens Thanks for the latest PRs. If you're interested in contributing further you can join our slack channel to discuss ideas / ask questions 

https://join.slack.com/t/nuxtent/shared_invite/enQtMjQ1MzI4MzgxNzI5LTcwOTlkYTczNTMzMGU1YjYyYjlkNzNjNDc3MjQ3YTdmMjc0ZThkZjM1ZWY4ZjhiZjc1MDIwYjJmMjAxODlhMzU
