### ISSUE TITLE
Generated Route is Correct, but Path generated for Content is Wrong

### ISSUE THREAD

**Issue by Towerism** [nuxt-community/nuxtent-module#109]
I know you guys fixed #103, but it seems the path generated for content is plagued by the same issue. I get this when querying content-api:
```
[{"title":"Hello World","meta":{"index":0,"fileName":"HelloWorld.md","section":"/","dirName":"/"},"date":"2017-10-21","path":"\\hello-world","permalink":"\\hello-world","anchors":[],"body":"<p>I started in the content directory and somehow made it all the way here!</p>\n"}]
```
Notice the paths and permalink here have double backslashes instead of just a single forward slash.

**Comment by medfreeman** [comment]
@Towerism i'll have a look tonight, just know that things will become better when i'll have access to automated windows builds, preventing further regressions.
I have literally no occasion to directly test nuxtent on windows.

**Comment by alidcastano** [comment]
@medfreeman Atinux says access has been granted!

**Comment by alidcastano** [comment]
Btw, likely related to #94

**Comment by alidcastano** [comment]
I fixed the `path`, `permalink`, and `relativePath` properties by replacing then backslash with regex. Should be working by next release!
