### ISSUE TITLE
anchors array is always empty

### ISSUE THREAD

**Issue by vinaypuppal** [nuxt-community/nuxtent-module#111]
- I am trying out this [content-navigation](https://github.com/nuxt-community/nuxtent-module/tree/master/examples/content-navigation) example.
- And from this [comment](https://github.com/nuxt-community/nuxtent-module/issues/86#issuecomment-332521008) by @alidcastano 
    > Also, you have access to page anchors (headings inside page), so you can use those for within-page navigation if the content page is long. (For a reference, here's the content navigation example.)

- When I access content-api, I see empty anchors array

**Comment by alidcastano** [comment]
Yes, that should be working. I use the automatic navigation feature it for the nuxtent and ency documentation sites, but perhaps a recent refactor that we did interfered with the behavior. We'll have to add tests for this and fix it, thanks for opening issue
