### ISSUE TITLE
Nuxt generated project has wrong axios call

### ISSUE THREAD

**Issue by XiangyuJamesZhang** [nuxt-community/nuxtent-module#118]
Hi guys,

I am using nuxtent to generate static site, here is my issue:

with such nuxtent config:
```javascript
  content: [
    [
      'project/node/',
      {
        page: 'project/node/_slug',
        permalink: 'project/node/:slug',
        isPost: false,
        generate: ['get', 'getAll']
      }
    ]
  ]
```
and content folder: 
```
content
  |- project
  | |- node
  | | |- post1.md
  | | |- post2.md
```
`nuxt generate`will create something like
```
dist
  |- _nuxt
  | |- content
  | | |- project
  | | | |- node
  | | | | |- project.node
  | | | | | |- post1.json
  | | | | | |- post2.json
```
however, after I host the dist folder and want to check **post1**, axios will ask resource from `https://domainname/_nuxt/content/project/node/project.node.post1.json`
and cause an error since the right path should be 
`https://domainname/_nuxt/content/project/node/project.node/post1.json`.
I can make thing work by adding a line in
https://github.com/nuxt-community/nuxtent-module/blob/8f7afaa87706b27b30b927371eadd88b2a2b6ec2/lib/plugins/requestContent.js#L37
 to replace the last dot to slash:
```
const allButFirstSlash = /(?!^\/)(\/)/g
const lastDot = /\.(?=[^.]*$)/
const serializedPermalink = permalink.replace(allButFirstSlash, '.').replace(lastDot,'/');
``` 
I think another solution is to rearrange how nuxtent generate nuxt routes in 
https://github.com/nuxt-community/nuxtent-module/blob/8f7afaa87706b27b30b927371eadd88b2a2b6ec2/lib/content/build.js#L122
to make nuxt generate based on page path and content name

**Comment by alidcastano** [comment]
Is a folder named `project.node`? If so then yea it uses regex to match routes so we'd need to improve the command but this is a pretty unusual case, not sure if it is even recommended to use periods in file names

**Comment by XiangyuJamesZhang** [comment]
Yeah. I don't think it is an unusual case. It seems like if the permalink contains path
>in order to inject right path to the nuxt->generate->router config https://github.com/nuxt-community/nuxtent-module/blob/8f7afaa87706b27b30b927371eadd88b2a2b6ec2/lib/content/build.js#L121-L124

then the generated nuxtent content folder in dist will contain periods in file names.
I dislike those periods either but I have no choice. As I said, maybe it's better to leave permalink out of path info, and inject both path and permalink in the code above

Anyway, thank you so much to create this tool, the normal SSR function works pretty well. But I have to use nuxt and nuxtent to generate static site, so...

**Comment by alidcastano** [comment]
I'm sorry I'm not fully understanding - is an error only occurring when you generate the content? If so then yes it deals with the build file. 

The problem likely lies here: 
https://github.com/nuxt-community/nuxtent-module/blob/8f7afaa87706b27b30b927371eadd88b2a2b6ec2/lib/content/build.js#L5-L12

Feel free to do a PR and if you have questions you can ask them in the [slack channel](https://join.slack.com/t/nuxtent/shared_invite/enQtMjQ1MzI4MzgxNzI5LTcwOTlkYTczNTMzMGU1YjYyYjlkNzNjNDc3MjQ3YTdmMjc0ZThkZjM1ZWY4ZjhiZjc1MDIwYjJmMjAxODlhMzU)

**Comment by XiangyuJamesZhang** [comment]
cool, I will give it a try
