### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of path.match

### ISSUE THREAD

**Issue by AWulkan** [nuxt-community/nuxtent-module#124]
I installed the starter template and ran `npm run dev` to get this error below.

```
NuxtServerError

Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of path.match at
 getSection (C:\Users\USER\Desktop\vue\nuxtent\my-
site\node_modules\nuxtent\dist\loader.js:19:33) at Object.module.exports
 (C:\Users\USER\Desktop\vue\nuxtent\my-
site\node_modules\nuxtent\dist\loader.js:114:19)
```

```js
node_modules\nuxtent\dist\loader.js
}

const getSection = path => {
  // capture '/content/closestSubsection' or  '/content'
  // eslint-disable-next-line no-unused-vars
  const [match, section] = path.match(/\/content([/][a-zA-Z\-_]*|$)/)
  return section === '' ? '/' : section
}

const getComponentBaseName = (baseDir, name, extensions) => {
  const baseName = join(baseDir, name)
```
Js
getSection@19:33  

Windows 10
Node 8.9.1
Latest Nuxtent version

**Comment by sebtiz13** [comment]
Duplicate #94 
You do compile module from branch master

**Comment by AWulkan** [comment]
@sebtiz13so I can't install it through npm? I'm not sure I understand.

Any estimation on when the fix will be released in the next version?

**Comment by sebtiz13** [comment]
@AWulkan Exactly the version released on npm doesn't work on windows.
You do to wait a new release on npm or compile manually the package from branch master.
The bug is solved but i don't know why the new version is not released.

**Comment by AWulkan** [comment]
@sebtiz13 Ok, thanks. I will just use another generator for now then. Maybe I'll come back to this once it's released.

**Comment by AWulkan** [comment]
Why was this reopened if fit's already solved?

**Comment by alidcastano** [comment]
Sorry, I've been incredibly busy but I know that people use this plugin for their blogs and do intend to publish the working windows version at some point (just need to make sure it doesn't break anything etc.). I reopened it as a reminder.
