### ISSUE TITLE
Can not do cache or prefetch on asyncData?

### ISSUE THREAD

**Issue by qwIvan** [nuxt-community/nuxtent-module#130]
<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c105">#c105</a>)</em></sub></div>

**Comment by alidcastano** [comment]
Can you show me an example of what you're trying to accomplish?

**Comment by qwIvan** [comment]
The browser needs to send a HTTP request when it navigates backward or forward, even if the page has been visited.
I think it should have direct access to the cache.

**Comment by cesasol** [comment]
Closed thanks to the work of @joostdecock currently on the development branch.
