### ISSUE TITLE
Working with arrays in yaml files

### ISSUE THREAD

**Issue by misscs** [nuxt-community/nuxtent-module#131]
First time working with vue and nuxt. I'm bit baffled as to how to iterate through an array in a yaml file. 

As an example, yaml file would contain a list:

```
items:
  - 
    type: talk
    event: A decent talk
  - 
    type: workshop
    event: A long workshop
```

In my template, I'm getting the content

```
  async asyncData ({ app }) {
    return {
      talks: await app.$content('speaking').getAll()
    }
  }
```

This is the return when I look into the `/content-api`

```
[
{
meta: {
index: 0,
fileName: "talks.yaml",
section: "/",
dirName: "/speaking"
},
date: "2018-01-01",
path: "/speaking/speaking/talks",
permalink: "/speaking/talks",
anchors: [ ],
body: {
items: [
{
type: "talk",
event: "A decent talk"
},
{
type: "workshop",
event: "A long workshop"
}
]
}
}
]
```

I would expect to be able to iterate through it with either `v-for="talk in talks.items"` or `v-for="talk in talks" or `v-for="talk in talks.body.items"` but none of them work—the screen is blank. 

However, I can access data from yaml files if it is not in an array. 

I feel like I'm missing a very simple. Thanks in advance.

**Comment by dahrens** [comment]
As you can see you have an array with objects (per file) - what you might do is:

```html
<template v-for="speaking in speakings">
    <template v-for="talk in speaking.body.items">
        {{ talk.event }}
    </template>
</template>
```

Some recommendations and explanaitions:

I assume you have an folder called `speakings` in your `content` folder.

nuxtent expects files in this folder. Each file represents one speaking.

When you use nuxtents content API `app.$content('speaking').getAll()` it parses whole the directory and returns a list of JSON objects which look like this:

```
{
  meta: {
    index: 0,
    fileName: "talks.yaml",
    section: "/",
    dirName: "/speaking"
  },
  date: "2018-01-01",
  path: "/speaking/speaking/talks",
  permalink: "/speaking/talks",
  anchors: [ ],
  body: {
    talks: []
  }
}
```

The data specified in each of your files lives inside the body attribute. Other data around was gathered by nuxtent based on your configuration.

I suggest that you create two files in the speakings folder like that:

**decent_talk.yaml**

```yaml
type: "talk",
event: "A decent talk"
```

**long_workshop**

```yaml
type: "workshop",
event: "A long workshop"
```

Which would result in something like that -  I only show the first as an example:

```
[{
  meta: {
    index: 0,
    fileName: "decent_talk.yaml",
    section: "/",
    dirName: "/speaking"
  },
  date: "2018-01-01",
  path: "/speaking/speaking/decent_talk",
  permalink: "/speaking/decent_talk",
  anchors: [ ],
  body: {
    type: "talk",
    event: "A decent talk"
  }
}]
```

In a template you can use it like that

```html
<template v-for="speaking in speakings">
    {{ speaking.body.event }}
</template>
```

**Comment by alidcastano** [comment]
@misscs Did @dahrens answer your question? 

I'll close the issue but feel free to reopen it if not

**Comment by misscs** [comment]
Thank you @dahrens! I ended up moving everything into its own yaml file. Thank you for taking the time to explain and provide examples.
