### ISSUE TITLE
Load markdown files from CDN or external source

### ISSUE THREAD

**Issue by evanrlong** [nuxt-community/nuxtent-module#132]
I'm trying to load markdown files hosted on a CDN into a nuxt webapp using nuxtent.  My desired workflow would be...

1. Designers create or modify markdown files and push to CDN (or external file server)
2. Web app reads in markdown files from CDN and renders results using nuxtent

The goal is to allow designers to modify the content of a web app and have their changes reflected without an app rebuild/deploy.

I tried to connect nuxtent to an external service by modifying the baseUrl parameter but (as you mention [here](https://nuxtent.now.sh/guide/configuration)) that doesn't work since the nuxtent content server can't recognize external resources.

Is there a way to accomplish what I am looking for in nuxtent?

Thanks for the help.  I love the project!

**Comment by alidcastano** [comment]
Nuxtent was primarily created for local markdown files so I haven't looked into this - but If I remember correctly Nuxt.js site fetches external markdown files so I would look into how they did it.

Also, just noticed part of the docs that you linked to is a little outdated, will need to update

**Comment by evanrlong** [comment]
Awesome I'll take a look at the Nuxt.js site and see how they handle it.  At first glance, it looks like they are pre-rendering their markdown files into a similar json format to nuxtent (but only supporting pure html, no Vue components) and hosting that on their CDN.  See [here](https://docs.api.nuxtjs.org/releases).  Then they are loading the json files into the app with axios and rendering the html in their components using v-html.  [Here](https://github.com/nuxt/nuxtjs.org/blob/master/pages/guide/release-notes.vue).

That seems like a reasonable approach.  I'll look into it for my site.  Thanks for the quick response and for pointing me in the right direction.

**Comment by alidcastano** [comment]
yes you'll need to fetch it yourself and convert the markdown files to HTML or JSON so that you can use it inside components (I look at their site as an example while building Nuxtent)

Best of luck, I'll go ahead and close this issue but feel free to reopen it if something comes up
