### ISSUE TITLE
Upgrading to nuxt 1.0

### ISSUE THREAD

**Issue by cesasol** [nuxt-community/nuxtent-module#134]
1.0 bring many changes and it breaks the generate method with this plugin. I try to look for documentation from nuxt to upgrade this package since almost all of the sites on my team uses it, but I could not find any.

**Comment by alidcastano** [comment]
https://github.com/nuxt-community/nuxtent-module/pull/135

**Comment by joostdecock** [comment]
New effort to get this done in https://github.com/nuxt-community/nuxtent-module/pull/146

**Comment by alidcastano** [comment]
This should work now with nuxtent@1.4 (or nuxtent@latest)!

Thanks for PRs @joostdecock and @cesasol
