### ISSUE TITLE
Breaking changes in 1.2, not mentioned in changelog

### ISSUE THREAD

**Issue by danhawkes** [nuxt-community/nuxtent-module#142]
Hi,
I've just spent a couple of hours trying to figure out why my code highlighting has stopped working, and  eventually found that `1.2.x` includes a breaking change (2945d4313850be5d1e894d912efc8859948c2ef6) in the `nuxtent.config.js`.  

The changelog seems to be out of date - the most recent entry is for `1.1.0`, and it looks like the npm release task hasn't been used for the past few releases based on the tag format. 

Is the intent to continue using `standard-version`, and if so, could some docs be added to `CONTRIBUTING.md` or similar to describe the release procedure?

**Comment by alidcastano** [comment]
Hi @danhawkes I'm so sorry about that. @medfreeman helped standardized the module but I unknowingly made that last few releases following the wrong procedure 

I added the documentation for the releases under Github's releases (https://github.com/nuxt-community/nuxtent-module/releases)

I'll take a look at how nuxt.js does it and follow that

Thanks for bringing this up

**Comment by danhawkes** [comment]
@alidcastano I see them, that's great! Thank you and @medfreeman for all your work on this project.
