### ISSUE TITLE
Consider streaming content html

### ISSUE THREAD

**Issue by qm3ster** [nuxt-community/nuxtent-module#144]
## [`document.write()` AND `iframe`? We have to add this!](https://jakearchibald.com/2016/fun-hacks-faster-content/#using-iframes-and-documentwrite-to-improve-performance)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c113">#c113</a>)</em></sub></div>

**Comment by cesasol** [comment]
We will leave this kind of optimization to vue and the userland (programmer).

**Comment by qm3ster** [comment]
Vue isn't concerned with massive chunks of preformatted text, and userland cannot be trusted

**Comment by cesasol** [comment]
I still think this is fall into the overoptimization problem and will take way to much work and not that much of a benefit for most developers and users using nuxtent. However you are welcome to discuss on gitter or discord. And if you would like to contribute implementing this feature I would suggest to wait unitl we release 3.0.
