### ISSUE TITLE
 incorrect HTML markup

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#15]
Getting the following warning:

```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```
Seems like the problem has to do with the way JSX plugin is rendering HTML, as the issue dissapears if the HTML is rendered via `v-html` directive in a vue template.

Opened issue on JSX: https://github.com/vuejs/babel-plugin-transform-vue-jsx/issues/90

Current workaround is to check if `body` is a component or HTML, if it's a component use `nuxtent-body`, if its HTML use `v-html`:

For example: 

```
component(v-if="isObject(post.body)" :is="post.body")
div(v-else v-html="post.body")
```

**Comment by medfreeman** [comment]
It seems the corresponding issue vuejs/vue#6519 has been closed 4 days ago.
In the meantime i had this as a workaround component, but probably not useful anymore:
```
import Vue from "vue";

Vue.component("nuxtent-body-fix", {
  render: function(h) {
    if (this.isObject(this.body)) {
      return h("nuxtent-body", {
        props: {
          body: this.body
        }
      });
    } else {
      return h("div", {
        domProps: {
          innerHTML: this.body
        }
      });
    }
  },
  methods: {
    isObject(body) {
      return typeof body === "object";
    }
  },
  props: {
    body: {
      type: [Object, String],
      required: true
    }
  }
});
```
