### ISSUE TITLE
Directly going to permalink fails? Generate command fails as well

### ISSUE THREAD

**Issue by dimitrieh** [nuxt-community/nuxtent-module#152]
Hi! Just tried to implement the new Nuxt version into my application. Got everything set up pretty nicely and it does seem to work to some extent, however...

Working from macOS 10.13.3

Problems:
- When running `dev`, I can navigate towards the post through the `nuxt-link` elements. However when directly using the permalink.. I get a `Error: read ECONNRESET`
- When running `generate`, it fails at some point. For the log please see these details:

Some help is very much appreciated. Are these errors my fault? Or are these lingering bugs to be solved after the recent merge of https://github.com/nuxt-community/nuxtent-module/pull/151 😃 

<details>
<pre><code>
  ...
  nuxt: Call build:done hooks (1) +47s
opening server connection
  nuxt: Call generate:distRemoved hooks (1) +6ms
  nuxt:generate Destination folder cleaned +47s
  nuxt: Call generate:distCopied hooks (1) +228ms
  nuxt:generate Static & build files copied +228ms
  nuxt:render Rendering url /schoolinstelling +0ms
  nuxt:render Rendering url /kind +73ms
  nuxt: Call generate:page hooks (1) +2s
  nuxt: Call generate:page hooks (1) +723ms
  nuxt:generate Generate file: /schoolinstelling/index.html +3s
  nuxt:generate Generate file: /kind/index.html +0ms
  nuxt:render Rendering url /ouders +3s
  nuxt:render Rendering url / +8ms
  nuxt:render Rendering url /ouders/whut +9ms
  nuxt: Call generate:page hooks (1) +662ms
  nuxt:generate Generate file: /index.html +661ms

 ERROR

  Error: read ECONNRESET

  - util.js:1026 _errnoException
    util.js:1026:11

  - net.js:606 TCP.onread
    net.js:606:25

 ERROR

  Error: read ECONNRESET

  - util.js:1026 _errnoException
    util.js:1026:11

  - net.js:606 TCP.onread
    net.js:606:25

  nuxt:render Rendering url / +690ms
  nuxt: Call generate:done hooks (2) +54ms
  nuxt:generate HTML Files generated in 51.3s +54ms

 Generate errors summary:

 ROUTE  /ouders

  Error: read ECONNRESET

  - util.js:1026 _errnoException
    util.js:1026:11

  - net.js:606 TCP.onread
    net.js:606:25

 ROUTE  /ouders/whut

  Error: read ECONNRESET

  - util.js:1026 _errnoException
    util.js:1026:11

  - net.js:606 TCP.onread
    net.js:606:25

closing server connection
  nuxt:generate Generate done +7ms
Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)
Error: read ECONNRESET
    at _errnoException (util.js:1026:11)
    at TCP.onread (net.js:606:25)

npm ERR! Darwin 17.4.0
npm ERR! argv "/usr/local/Cellar/node/8.5.0/bin/node" "/Users/dimitrie/.node/bin/npm" "run" "generate"
npm ERR! node v8.5.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! stichtingnatuurlijkverder@1.0.0 generate: `nuxt generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stichtingnatuurlijkverder@1.0.0 generate script 'nuxt generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the stichtingnatuurlijkverder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs stichtingnatuurlijkverder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls stichtingnatuurlijkverder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dimitrie/Projects/snv-website/npm-debug.log
</code></pre>
<br>
<p>nuxtent.config:</p>
<pre><code>
module.exports = {
    content: [
        [
            'ouders',
            {
                page: '/ouders/_slug',
                permalink: '/ouders/:slug',
                isPost: false,
                generate: ['get', 'getAll']
            }
        ]
    ]
}
</code></pre>
</details>

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c118">#c118</a>)</em></sub></div>

**Comment by dimitrieh** [comment]
> Some help is very much appreciated. Are these errors my fault? Or are these lingering bugs to be solved after the recent merge of #151 😃

Just tested this out with the template project from my previous comment. And this generates the exact same problems if I change the `package.json` dependencies to: 

```
  "dependencies": {
    "@nuxtjs/axios": "^5.1.1",
    "nuxt": "^1.4.0",
    "nuxtent": "^1.4.1"
  },
```

So a good test case to solve these errors :)

cc: @alidcastano @apmontgomery @joostdecock (this might interest you, as you were involved with https://github.com/nuxt-community/nuxtent-module/pull/151 )

**Comment by joostdecock** [comment]
Did you configure the `browserBaseURL` ?


An example config could be something like:

```
api: {
  baseURL: 'http://localhost:3000',
  browserBaseURL: 'http://my-production-domain.com'
}
```

**Comment by alidcastano** [comment]
What's the difference between baseUrl and browserBaseUrl? Not sure when/why this changed

**Comment by joostdecock** [comment]
From my (limited) understanding, `baseURL` is used during build time, or when running in Dev.

`browserBaseURL` is used after the build is completed.

So, when you run `nuxt generate` it will use baseURL` during the build to contact the nuxtent content-api.

But the code in dist will use `browserBaseURL` to contact the content-api.

I figured this out because when I ran generate, my statically build HTML was still contacting `http://localhost:3000` but because I'm deploying on a static web server, that makes no sense.

Arguably, it should just use `/content-api` as a relative url, but I haven't tried to see if setting`browserBaseURL` to `/` would do the trick.

**Comment by apmontgomery** [comment]
this issue is with @nuxt/axios 5.x
downgrade to @nuxt/axios 4.5.2 and you'll be fine.  Looks like we need to upgrade some of the code in nuxtent to handle breaking changes from @nuxt/axios 4 -5 
https://axios.nuxtjs.org/migration.html

**Comment by apmontgomery** [comment]
and looks like @joostdecock is also correct.  if you set nuxtent's browserBaseURL in nuxtent.config then it will work with the latest nuxt/axios


```
api: {
    baseURL: 'http://localhost:3000',
    browserBaseURL: 'http://localhost:3000'
  }
```

**Comment by dimitrieh** [comment]
Thanks for all the help here! Seems to work out fine! 😄 

Is there a way to configure this for both online (base url can change) and offline environments?  (I think I need the older axios for that now correct?)

**Comment by dimitrieh** [comment]
Slightly off topic, but is it possible to have the 

Aggregate the slug items for nav purposes in a reusable component? It seems I have problems with the following:

```
[Vue warn]: Property or method "ouders" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <Navbar> at components/AppNavbar.vue
       <Index> at pages/index.vue
         <Nuxt>
           <Default> at layouts/default.vue
             <Root>
```

**Comment by joostdecock** [comment]
> Is there a way to configure this for both online (base url can change) and offline environments? (I think I need the older axios for that now correct?)

For online, you need to configure the `browserBaseURL` as mentioned above.

>  is it possible to aggregate the slug items for nav purposes

You can contact the content-api in your `asyncData`. Something like:
```
export default {
    asyncData: async function ({ app, route }) {
        var foo =  await app.$content('/blog').getAll();
        return { posts: foo }
    }
}
```

This will populate a `posts` car that you can iterate over.

**Comment by dimitrieh** [comment]
Going to document my found solution here as well for others to find.

Nuxt does its magic for async data functions only inside of the pages directory. When having a component inside of the components directory, you need to define the async data function inside of all of the pages that component is going to be rendered in.. inside the component you can define a prop in the meanwhile

**Comment by dimitrieh** [comment]
for doc purposes:

browser url can also be set with env variable for production purposes:

https://nuxtjs.org/api/configuration-env/    

```
api: {
        baseURL: process.env.BASE_URL || 'http://localhost:3000',
        browserBaseURL: process.env.BASE_URL || 'http://localhost:3000'
    }
```
