### ISSUE TITLE
How to reference an image inside your nuxtent markdown content file?

### ISSUE THREAD

**Issue by dimitrieh** [nuxt-community/nuxtent-module#161]
I could not find this anywhere in the documentation, so I think its best to get this issue out there.

When using HTML or markdown, the following does not work:

`![img](~/assets/img/image.jpeg)`

or 

`<img src="~/assets/img/image.jpeg">`

Help is appreciated! If I find out myself, I will document here! 😉

**Comment by dimitrieh** [comment]
should this be closed instantly due to a bot? cc: @joostdecock

**Comment by joostdecock** [comment]
Please create your issue through https://nuxtjs.cmty.io

This is a new policy that applies to all nuxt-community repos.

**Comment by dimitrieh** [comment]
done https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c123

**Comment by ishitatsuyuki** [comment]
You can use `.comp.md` because it's loaded through webpack. If you can, document it as well!

**Comment by dimitrieh** [comment]
@ishitatsuyuki can you elaborate? :)

**Comment by ishitatsuyuki** [comment]
@dimitrieh Change the content file extension to `.comp.md` so it's loaded into the Webpack bundle. At there Webpack import syntax will just work.

**Comment by ishitatsuyuki** [comment]
@dimitrieh The article markdown, of course.

**Comment by easherma** [comment]
This is not clear at all

**Comment by cesasol** [comment]
This module compiles to html as is and it outputs as html, there is no webpack parsing for the content inside the markdown files, so any image or asset should be static.

For the contrary if you use choose to use components (By using .comp.md extension) then it is parsed by webpack and the alias are applied.

**Comment by cesasol** [comment]
@easherma The documentation does not currently explain this behavior and I'm currently working on fixing some bugs and inconsistencies on the development branch.
