### ISSUE TITLE
Give the ability to render the slug without dates

### ISSUE THREAD

**Issue by mgrandl** [nuxt-community/nuxtent-module#173]
My posts look like this

`['posts', {
  page: '/posts/_slug',
  permalink: '/:year/:month/:day/:slug',
  isPost: true,
  generate: ['get', 'getAll']
}]`

Now I want my permalinks not to look like this `/2018/05/28/2018-05-28-lorem-ipsum` but instead like this `/2018/05/28/lorem-ipsum` how do I make this happen?

**Comment by cesasol** [comment]
I will look into this. But as this may potentially break current running sites and permalinks there should be a extra config like `dontRenderDateInSlug: true`

**Comment by joostdecock** [comment]
Pretty sure this is already possible, look no date in slug: https://freesewing.org/blog/announcing-penelope
