### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by fredDesign** [nuxt-community/nuxtent-module#174]
Hi,

I'm getting the following error on run dev

This dependency was not found:

* /Users/projets/my-site-nuxtent/.nuxt/client.js in multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

**Comment by cesasol** [comment]
This doesn't seem a problem with nuxtent. Can you confirm that removing nuxtent from your modules this problem does not appear?
