### ISSUE TITLE
Online documentation unavailable

### ISSUE THREAD

**Issue by renestalder** [nuxt-community/nuxtent-module#176]
### Version

[1.4.1](https://github.com/nuxtent-module/releases/tag/1.4.1)

### Reproduction link

[https://nuxtent.now.sh/](https://nuxtent.now.sh/)

### Steps to reproduce

VIsit https://nuxtent.now.sh/

### What is expected ?

Online documentation to be available.

### What is actually happening?

Getting 402 payment required

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtent-module/issues/c137">#c137</a>)</em></sub></div>

**Comment by ptdev** [comment]
Yes I can confirm this.
If you need to read them, and in case you don't know, when using Chrome you can just add "cache:" before the url and you should be able to access google's cache of the website. and still read the docs.

**Comment by jfcieslak** [comment]
Would you consider deploying the docs to something free and capable of serving static pages? like github pages or netlify.com ?

**Comment by cesasol** [comment]
I published the documentation on https://nuxtent-module.netlify.com

And since I don't have admin access to the repo @joostdecock or @alidcastano should update the description on the repo.

>  Someone else has the domain nuxtent.netlify.com with a broken site, hopefully some day it may be willing to give it so we can have a nicer url.

**Comment by joostdecock** [comment]
I've updated the URL in the description, and in the README.

**Comment by renestalder** [comment]
Thanks a lot, @cesasol, @joostdecock

**Comment by matjaeck** [comment]
Hi, seems the homepage is down again (../guides works).
