### ISSUE TITLE
✖ error TypeError: request.charCodeAt is not a function

### ISSUE THREAD

**Issue by cesasol** [nuxt-community/nuxtent-module#179]
### Version

[development](https://github.com/nuxtent-module/releases/tag/development)

### Reproduction link

[http://infiniti.dinamo.mx/](http://infiniti.dinamo.mx/)

### Steps to reproduce

Run yarn dev and using markdown components

### What is expected ?

Run without problems, even in threaded mode

### What is actually happening?

There is a weird message when using nuxt-edge that appears when runing in dev mode complaining about not finding a markdown module. This breaks threaded mode

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxtent-module/issues/c139">#c139</a>)</em></sub></div>

**Comment by laugharn** [comment]
I don't have Nuxtent but I do get this error from the latest nuxt-edge. It's not present in 2.0.0-25569931.85a8af5 but is present in 2.0.0-25573630.6bfa68d
