### ISSUE TITLE
404 when using nuxt programmatically with express-template

### ISSUE THREAD

**Issue by roikiermedia** [nuxt-community/nuxtent-module#25]
I setup a project with the [nuxt-community/express-template](https://github.com/nuxt-community/express-template) and installed the nuxtent module (^0.2.27). When i now start the dev-server `npm run dev` nuxtent returns a 404 status code for all content pages. The same happens on the /content-api route. 
When the project is started via the `nuxt` command everything works as expected.

**Comment by alidcastano** [comment]
Are they using the same dev url? You might have to configure the `baseURL` to match the nuxt starter one.

```js
module.exports = {
  api: {
    baseURL: (isProd) => isProd ? 'https://production-url.com' : 'http://localhost:3000'
  }
}
```
If this is the proble, look at the custom build for a complete config example. This will also be added to docs in next version.

**Comment by roikiermedia** [comment]
The template uses the same url, but even after setting the `baseURL` explicitly, no content is returned.

**Comment by alidcastano** [comment]
Ah, since `content-api` is returning 404 too, then using Nuxt programmatically likely interferes with `serverMiddleware`, which is how the content endpoint is setup. Might have to give the option to use Nuxtent programmatically as well for this to work.

**Comment by alidcastano** [comment]
Seeing with Nuxt team if there's a way to setup `serverMiddleware` programmatically, if there isn't I'll add hooks to make it possible with `Nuxtent`.

**Comment by roikiermedia** [comment]
Nice. Thanks for your work!

**Comment by alidcastano** [comment]
Can you try setting this line ( https://github.com/nuxt-community/express-template/blob/master/template/server/index.js#L7) to `http://localhost:3000` and/or set baseURL to `'127.0.0.1:3000'`.

**Comment by alidcastano** [comment]
Hey @roikiermedia what's your use case for wanting to use your own express server? This project was mainly meant for documentation sites, personal sites, etc. which is why I integrated into Nuxt as a module with only `serverMiddleware` option (which I feel should still work programmatically... I'll have to try it out).
