### ISSUE TITLE
add query option to content request methods

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#27]
So that you can include, exclude, filter, map etc. and return the processed output. 

Ex:

```
content: {
routes: {
   getAll: { 
       name: 'route-name', 
       process: (pages) =>{
         // e.g. include or exlcude data
       }
     },
    query: {
        name: 'another-route',
        process: (pages) => {
         // e.g. filter pages
       }
    }
 }
}

```

**Comment by alidcastano** [comment]
@levibostian

**Comment by alidcastano** [comment]
One constraint that would need to be made is that only one bundle of json content is allowed per route.

**Comment by levibostian** [comment]
As I have been toying around with this idea over night, the biggest piece of value we can provide to give the ability of collections is by allowing someone to query nuxtent content to get X number of results back ordered by some key. 

```
app.$content('/sectionname').getAll().latest(3, 'date')
```

The `latest()` function above is pretty self-explanatory. 

Then, with `v-for` I should be able to iterate `app.$content('/sectionname').getAll().latest(3, 'date')` to get all of the data that I need to display the content on my page with front matter included.

**Comment by alidcastano** [comment]
While this makes API easier, the only drawback with doing it this way is that you're still fetching ALL the data, when you might only need the data from the latest 3 posts.

Imagine at scale, rendering 1000 posts and then filtering to latest 3. Versus, just getting the latest 3 via their file name on the server and then sending them over to the client.

**Comment by alidcastano** [comment]
After thinking this through, the option to process the data must be sent via the client to server as url query params, and cannot be specified in config if the data is to be used dynamically.

**Comment by levibostian** [comment]
Isn't the data fetched server side using `asyncData` though?

**Comment by alidcastano** [comment]
Sorry, poor use of words–I meant "client" as in Nuxtent page and server as in "serverMiddleware".

So instead of processing data in Nuxtent config, it'll be done as you mentioned, in `asyncData`: 

for example, to exclude body from the data of requested pages:
```
await app.$content('/projects').query({ exclude: 'body' }).getAll()
```
And the request wrapper will fetch the content by sending the following request to serverMiddleware: 

```
/projects?exclude=body
```

**Comment by alidcastano** [comment]
So basically in next version you can now pluck unnecessary properties from page data. For example, if fetching pages to create navigation, you don't need the content `attributes` or `body`.

**Comment by alidcastano** [comment]
Still not sure if I want to add the option to filter pages, e.g. `sort` or `latest` since I'm not sure it'll make a huge difference letting user do this.

**Comment by levibostian** [comment]
As I have mentioned in previous issues, being able to cut down on compile time and payload is a good thing (really, isn't it always a good thing?). Good work. 

As of being able to filter pages, I am already doing this myself. I wrote some functions to sort by the date front-matter and then give me the first 3 objects from the array. It would be nice to be able to do this without having to write my own function each and every time I want to do it, but adding it to core isn't necessary. I could create a module for that if I wanted to extend the functionality.
