### ISSUE TITLE
Nuxtent content pages do not allow Vuejs components before <nuxtent-body/>

### ISSUE THREAD

**Issue by levibostian** [nuxt-community/nuxtent-module#28]
On my site that I am using Nuxtent with, here is an example Nuxtjs page that I have:

```
<template lang="pug">
  .w-100
    Navbar
    h1  {{ post.title }}
    nuxtent-body(:body="post.body")
</template>

<script>
import Navbar from '~components/Navbar.vue'

export default {
  components: {
    Navbar
  },
  asyncData: async ({ app, route, payload }) => ({
    post: await app.$content('/freelance').get(route.path) || payload
  })
}
</script>

<style lang="scss">
@import "~assets/css/main.scss";
</style>
```

When I browse to `127.0.0.1:3000/freelance/projectname`, I successfully see the content from my .md file: `content/freelance/projectname`. Nuxtent is setup correct there. 

Now, here is the problem. 

In my page template HTML, if I specify Vuejs components *before* `<nuxtent-body>`, those Vuejs components get removed when the browser renders the page. 

```
<template lang="pug">
  .w-100
    Navbar <------ When refresh my webpage, I do *not* see this HTML in the resulting screen. 
    h1  {{ post.title }} <--- I see this. 
    nuxtent-body(:body="post.body") <---- And I see this. 
</template>
```

Here is the resulting screen in my browser:

<img width="1280" alt="screen shot 2017-07-25 at 11 14 56 am" src="https://user-images.githubusercontent.com/2041082/28582362-a52f93e0-712a-11e7-8652-7b9c7835502b.png">

with the Vue dev browser plugin output. It says that my Navbar component is added to the page?

<img width="1003" alt="screen shot 2017-07-25 at 11 15 09 am" src="https://user-images.githubusercontent.com/2041082/28582380-b7f0c026-712a-11e7-97af-44964ec5141d.png">

Now, if I add the Navbar component *after* `<nuxtent-body>`, then the component shows up on the page:

```
<template lang="pug">
  .w-100
    h1  {{ post.title }}
    nuxtent-body(:body="post.body")
   Navbar <---- Move this below nuxtent-body
</template>
```

Here is the resulting screen in my browser:

<img width="1279" alt="screen shot 2017-07-25 at 11 17 42 am" src="https://user-images.githubusercontent.com/2041082/28582432-f94e28ce-712a-11e7-8e13-7aa934d93f02.png">

You can see my Navbar now. 

*side note: Notice that in this screenshot above ^^^^ you cannot see the word "Static" anymore. I tried to add some CSS to the `<nuxtent-body>` tag to add some padding to the top so that my Navbar would not cover up any content (the Navbar component is fixed positioning to the top) and none of the CSS properties stayed in tact on the `<nuxtent-body>` component. They all got removed. 

When I load up my browser, for a split second I can see my Navbar and the CSS styles. It is after the async operation is complete fetching the post content that nuxtent removes everything. 

Goal: I want to be able to have Vuejs components above `<nuxtent-body>` so that I can style my content pages.

**Comment by levibostian** [comment]
You can browse and run my code at this state via repo: https://github.com/levibostian/levibostian.com/tree/90a9b1d88dba8e34869728163c9e0f971d3b7de5

**Comment by alidcastano** [comment]
Are you trying to render HTML? If so can you try rendering it with`v-html="post.body"`. Let me know if that makes a difference. 

Going to handle some other issues first (https://github.com/nuxt-community/nuxtent/issues/22, https://github.com/nuxt-community/nuxtent/issues/27), then I'll look at this.

**Comment by levibostian** [comment]
When I change `nuxtent-body.mt5(:body="post.body")` to `nuxtent-body.mt5(v-html="post.body")` and load up site in browser, Vue throws an error:

<img width="338" alt="screen shot 2017-07-25 at 1 20 19 pm" src="https://user-images.githubusercontent.com/2041082/28587268-27307344-713c-11e7-8754-be3e3abe4384.png">

**Comment by alidcastano** [comment]
v-html is  vue directive for rendering HTML, unreleated to Nuxtent.

It would be `div(v-html="post.body")`

--

The reason I ask is to see if it is related to https://github.com/nuxt-community/nuxtent/issues/15, which is a problem with JSX rendering HTML. 

`nuxtent-body` is just a component that checks if the content body is HTML or a component and renders with JSX appropriately.

So in the meantime, you can just do it yourself (assuming that's the error), since you can do it with a Vue template rather than a render function to avoid the errors.


If you need both HTML and component - just check if body is an object: 

 ```
component(v-if="isObject(post.body)" :is="post.body")
div(v-else v-html="post.body")
```

**Comment by levibostian** [comment]
Yes, `div(v-html="post.body")` does the trick. My markdown content is being shown. 

At the moment, I do not need to declare components inside of my `.md` files so `div(v-html="post.body")` works for me at the moment. 

I should be good to go with this solution until the JSX issues are resolved.

**Comment by alidcastano** [comment]
Great I'll go ahead and close this. I'd be careful updating packages as it's still in WIP stage, unfortunately. Only update to package version in `releases` as anything between there are no guarantees.

**Comment by levibostian** [comment]
Understood. Thank you.
