### ISSUE TITLE
markdown components do not work with nuxt ^rc3 version

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#34]

**Comment by AlexeyKot** [comment]
Having the same issue with Nuxt rc4.
when trying to run a starting template with rc4 and running `npm run dev`, having this:
`
 WARNING  Compiled with 1 warnings                                                                              16:56:34

 warning  in ./content/HelloWorld.comp.md

Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
    at getSection (C:\Users\shadm\web\vue\nuxtent-example\node_modules\nuxtent\dist\loader.js:107:33)
    at Object.module.exports (C:\Users\shadm\web\vue\nuxtent-example\node_modules\nuxtent\dist\loader.js:54:19)

 @ ./content \.comp\.md$
 @ ./.nuxt/dist.plugin.fa48b0d6.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=$client&reload=true ./.nuxt/client.js

  nuxt:render Rendering url /_nuxt/c4e73848b834217d17d8.hot-update.json +0ms
  Error: Invalid character in statusMessage.

  - renderer.js:294 sendResponse
    [nuxtent-example]/[nuxt]/lib/core/renderer.js:294:11

  - nuxt.js:2215
    [nuxtent-example]/[nuxt]/dist/nuxt.js:2215:11


  nuxt:render Rendering url /_nuxt/manifest.c4e73848b834217d17d8.js +10s
  Error: Invalid character in statusMessage.

  - renderer.js:294 sendResponse
    [nuxtent-example]/[nuxt]/lib/core/renderer.js:294:11

  - nuxt.js:2215
    [nuxtent-example]/[nuxt]/dist/nuxt.js:2215:11
`

**Comment by alidcastano** [comment]
fixed with @medfreeman latest PR ( https://github.com/nuxt-community/nuxtent-module/pull/76)

**Comment by yoanmarchal** [comment]
which version of Nuxt do you got ?
I got this error on the first start

**Comment by alidcastano** [comment]
tested with rc11

**Comment by yoanmarchal** [comment]
ok i try with 

1. mac os X 10.11.6

- node 8.5.0
- npm 5.4.2 
i can run
`vue init nuxt-community/nuxtent-template my-site` 
no probs here

2. Windows 10
- node 8.6.0
- npm 5.3.0
i still got  error on compilation

> Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
at getSection (D:\projects\nuxt\my-site\node_modules\nuxtent\dist\loader.js:19:33)
at Object.module.exports (D:\projects\nuxt\my-site\node_modules\nuxtent\dist\loader.js:114:19)

**Comment by alidcastano** [comment]
Ok so the error is specific to windows, can you open up a new issue with the details? Thanks

**Comment by yoanmarchal** [comment]
done #94, sorry for my bad english
