### ISSUE TITLE
How to use nuxtent with i18n?

### ISSUE THREAD

**Issue by t0ker** [nuxt-community/nuxtent-module#40]
So im working on a quite big site that is very content heavy, however I will definitely need to add i18n to support multiple languages. Is it possible to use it with Nuxtent, and any tips on how? 

Thanks in advance

**Comment by alidcastano** [comment]
What plugin are you using? If you can show me a basic example of how you'd do it w/o Nuxtent, then I can show you how to apply that to Nuxtent

**Comment by t0ker** [comment]
I would have started out with the i18n example nuxtjs has. 

Here is the example: https://github.com/nuxt/nuxt.js/tree/dev/examples/i18n

Thanks

**Comment by alidcastano** [comment]
I will draft an example over the weekend. I might also add methods that offer better support for this.

**Comment by t0ker** [comment]
Btw, I keep running in to this issue:

on the blog page, everything is fetched as it should, but when actually viewing the post i get a 404.

**Comment by alidcastano** [comment]
It seems like you're saying `getAll` works but `get` all doesn't. Can you open up a new issue for this with some code? Unless it is another problem, it's likely that you're not passing the correct permalink to `get`. You need to pass either `route.path` or `params.slug` depending if the content is nested.

**Comment by t0ker** [comment]
The link is pointing in the right direction, when i land on the post its a 404. url is correct. 

Il open a new issue tonight :) thanks again

**Comment by alidcastano** [comment]
You don't really need a plugin for this actually. You just need to register each language as a separate content directory so that an API endpoint is created for each, and then fetch it appropriately inside Nuxt.js pages. 

Here's a basic example: https://github.com/nuxt-community/nuxtent-module/tree/master/examples/i18n
