### ISSUE TITLE
Make STATIC=true part of `nuxtent generate`

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#44]

**Comment by abattenburg** [comment]
Is there any documentation on what this does? When I run _'yarn generate'_ after putting 'STATIC=true' in my nuxtent.config.js, the blog portion of the site fails. Is 'nuxtent generate' and upcoming command to still allow the site to be exported statically? Thanks for the clarification!

**Comment by alidcastano** [comment]
For now instead of `nuxt generate` you can run `STATIC=true nuxtent generate`

**Comment by alidcastano** [comment]
Next version only requires `nuxtent generate` as the command.  `Static=true` is set automatically.

**Comment by abattenburg** [comment]
When I run `STATIC=true yarn nuxtent generate`, I get a type error. I'm using the template linked in the ReadMe and I have updated. Works perfectly when running in dev. Maybe I'm still misunderstanding the command? 

```
node_modules/nuxtent/bin/nuxtent-generate:57

const nuxt = new Nuxt(options)
             ^
```

**Comment by alidcastano** [comment]
No you're using it correctly now. Sorry for the complications, Nuxt is in a transitionary phase so you have to be mindful of versions you're using. Make sure you're using the lastest nuxt version if you want to to generate static version of site via nuxtent command (however, you won't be able to use markdown components yet with this version).

**Comment by alidcastano** [comment]
run `npm install nuxt@1.0.0-rc3`

**Comment by abattenburg** [comment]
Hm. Just updated to the beta and it built fine, but I then got a network error when I navigated to the markdown blogs when running in Dev, and also the same thing when testing the generated version on a webserver. I'm going to assume I messed up the template at some point and try again tomorrow from scratch.

Thank you for the guidance on this issue and all the work you've put into this module! I love the concept as an alternative to static site generators.

**Comment by alidcastano** [comment]
Feel free to open up a new issue with the error information otherwise. 

There is a 404 error caused by hot module reloading that I was getting as well, so it might be the same issue. I intend to fix it since it's annoying to see on the terminal but it shouldn't prevent the content from beign fetched and rendered.
