### ISSUE TITLE
Add sitemap example 

### ISSUE THREAD

**Issue by cesasol** [nuxt-community/nuxtent-module#45]
There is a way to automatically add the routes generated with nuxtent to the sitemap module?

**Comment by alidcastano** [comment]
I'll add an example soon.

Pretty sure you can just fetch content endpoint and get permalinks only.

e.g. `axios.get('content-api/posts').map(page => page.permalink)` 

Will need to verify this works though. :)

**Comment by alidcastano** [comment]
The sitemap example has been added: https://github.com/nuxt-community/nuxtent-module/tree/master/examples/sitemap
