### ISSUE TITLE
Update "Examples" projects

### ISSUE THREAD

**Issue by AlexeyKot** [nuxt-community/nuxtent-module#46]
Hi!

I wanted to try examples, so I downloaded your repo, went in "single-content-type" folder and tried `npm i`, but got error.
Looks like in your `package.json` you set a dependency like
`"nuxtent": "file:///Users/acastano/Sites/nuxt/nuxtent"`
which, of course, doesn't work.
Same is for other examples.
I'm nue to Nuxt and your project looks very interesting. Can you please update the examples?

**Comment by alidcastano** [comment]
I'll do that soon. I was waiting for Nuxt to stabilize before making more updates. For the examples I just have to install actual nuxt package rather than local version, but they should work aside from that.

**Comment by alidcastano** [comment]
Thanks for opening this up. All the examples have been updated! 

Feel free to touch base via new issue, or twitter, etc if you run into any problems.
