### ISSUE TITLE
isAPI not set correctly when using generate

### ISSUE THREAD

**Issue by josh--** [nuxt-community/nuxtent-module#47]
It looks like there might be an issue how IsAPI is being set within lib/plugin.js

https://github.com/nuxt-community/nuxtent-module/blob/master/lib/plugin.js#L35

when generating a static site isAPI is always true even when isClient is true. When serving the generated site via nginx the browser tries to load the "api" url rather than generated content one. I simply added the following, regenerated and it was good to go. 

```
  if(isClient){
    isAPI = false;
  }
```

**Comment by alidcastano** [comment]
Are you using `STATIC=true nuxtent generate`?  (Next release will just be `nuxtent generate` just need to publish it).

If so, then it should be set to false. Let me know.

**Comment by josh--** [comment]
perhaps it's something different but it definitely appears to be something going on with the that check.

when i run the command without `STATIC=true` it doesn't generate the dynamic routes.

when i run the command with `STATIC=true` it does generate the dynamic routes. so i'm pretty sure the variable is getting set correctly initially. 

problem is that even though i run the command with `STATIC=true` when I log the value of `process.env.STATIC` @ that point (https://github.com/nuxt-community/nuxtent-module/blob/master/lib/plugin.js#L35) it's always undefined.

**Comment by alidcastano** [comment]
I just tested this. If I put `console.log` right under that line, `process.env.STATIC` is a boolean and not undefined.

Can you try updating to the latest version?

**Comment by josh--** [comment]
Just tried again with the latest version (0.2.75). Still having the same issue. It generates everything fine, however browser still attempts to hit the wrong URL.

Digging in a little deeper it appears this is because `process.env` is not set at all on the client side. I believe the `process.env.STATIC` would some how need to be made available in the browser for it to work correctly.

**Comment by alidcastano** [comment]
Ok I just made it a closure. Try `nuxtent@0.2.76`

**Comment by josh--** [comment]
unfortunately not quite, still having the same issue. 

i think that its because in the browser context it never gets the `process.env.STATIC` variable set at any point.

**Comment by alidcastano** [comment]
Can you try `nuxtent@0.2.77`. I made it so you could pass `isStatic` via the nuxtent options. 

So in your config: 

```
module.exports: {
  isStatic: true
}
```

**Comment by josh--** [comment]
good to go now on my end
thanks again!

**Comment by alidcastano** [comment]
Awesome, when your site is up, feel free to add it to list in README if you like

**Comment by josh--** [comment]
sounds good, will do!
