### ISSUE TITLE
Permalink must be a string

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/nuxtent-module#49]
here is my config in nuxtent.config.js
```
module.exports = {
  content: {
    page: 'blog/_slug',
    permalink: ':slug',
    isPost: false,
    generate: [
      'get',
      'getAll'
    ]
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://wi-cuckoo.github.io'
      : 'http://localhost:3000'
  }
}
```

then the error occurred, why

**Comment by alidcastano** [comment]
You must pass either `route.path` or `params.slug` to the content helper methods.

For example:

```
app.$content('/').get(route.path)
``

How are you using the `$content` helper?

**Comment by wi-cuckoo** [comment]
Yeah, My _slug.vue look like below
```
 asyncData: async ({ app, route }) => ({
      post: await app.$content('/').get(route.slug)
    })
```

**Comment by alidcastano** [comment]
That's the problem, `route.slug` is undefined and not a string.

it should be `route.params.slug` or: 
```
 asyncData: async ({ params }) => ({
      post: await app.$content('/').get(params.slug)
    })
```

**Comment by wi-cuckoo** [comment]
actually I logged the route, and changed to route.params.slug, but the result is incorrect.

**Comment by wi-cuckoo** [comment]
And also I found some example can't work, So I didn't know which config is working. I just want the path looks like /blog/_slug. But whatever I can't success, as the example `multiple-content-types` can't work locally
