### ISSUE TITLE
cat it support generate github page file

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/nuxtent-module#50]

**Comment by wi-cuckoo** [comment]
I tried, but the github return 404

**Comment by alidcastano** [comment]
Are you having problems with this, or is the issue permanently closed now? If not, please be more clear in your description.

**Comment by wi-cuckoo** [comment]
I means, the nuxtent's README.md said that it can be build heavy content site like jeklly. I want to know if the nuxtent+nuxt can use in build my github page like jeklly. I doubt that nuxtent can't support like that

**Comment by alidcastano** [comment]
What do you mean by your github page? 

Nuxtent will improve as is required by usage. Right now I'm using it for my sites and it works well enough :)

**Comment by wi-cuckoo** [comment]
ooooh. Can I use it only in client render? I just want to deploy my-site as static file. Can you understand. And for this, the doc don't wirite.

**Comment by alidcastano** [comment]
Ok so you want to deploy your site via github pages.

Nuxt docs have information about how to do this: https://nuxtjs.org/faq/github-pages

Only difference is that you run `nuxtent generate`.

**Comment by alidcastano** [comment]
Please open a new issue if you run into any problems
