### ISSUE TITLE
Display the last blogs post in a sidebar or accordion

### ISSUE THREAD

**Issue by STnetwork** [nuxt-community/nuxtent-module#51]
Hi,

Is it possible to do something like that : https://learn.getgrav.org/cookbook/twig-recipes#list-the-last-5-recent-blog-posts, with the nuxtent-module ?
If it's possible how ? if I want display the last blogs post only about articles in "/example" folder ?

Thanks !

**Comment by alidcastano** [comment]
`app.$content('/articles').getAll() ` will return an array that you can do anyting with. 

For example:

```
asyncData: async () => ({
latestArticles: (await app.$content('/articles').getAll()).slice(0,5)
})
```

If you're not doing a static site, you can alway do: `app.$content('/articles').getOnly(0, 5)`

See: https://nuxtent.now.sh/guide/usage
