### ISSUE TITLE
error in run generate

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/nuxtent-module#52]
when run `npm run generate`, It will send axios request to node server which not exist.

```
nuxt:generate Generate file: /resume/index.html +258ms
  Error: connect ECONNREFUSED 0.0.0.0:8088
```
So I need to take a tricky way, by run server on a way, and run generate in another way. Can it be fixed

**Comment by alidcastano** [comment]
What is `npm run generate` calling? Please post the scripts in your `package.json`.

**Comment by wi-cuckoo** [comment]
here it is:

```
"scripts": {
    "dev": "HOST=0.0.0.0 PORT=8088 nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "HOST=0.0.0.0 PORT=8088 nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
```

**Comment by alidcastano** [comment]
It should be  "generate": "HOST=0.0.0.0 PORT=8088 nuxtent generate"

**Comment by wi-cuckoo** [comment]
If I do that, it can generate file which did by nuxt generate?

**Comment by alidcastano** [comment]
Yes, does all that `nuxt  generate` does plus runs `serverMiddleware` so that content api works when content is being compiled.

**Comment by wi-cuckoo** [comment]
Oh， that's would be perfect
