### ISSUE TITLE
weird baseUrl when run generate

### ISSUE THREAD

**Issue by wi-cuckoo** [nuxt-community/nuxtent-module#53]
# my nuxtent.config.js
```js
module.exports = {
  content: [
    ['blog', {
      page: '/blog/_slug',
      permalink: "/:slug",
      generate: ['get', 'getAll'],
      isPost: false
    }]
  ],
  api: {
   	baseURL: process.env.NODE_ENV === 'production'
	    ? 'http://wi-cuckoo.io'
	    : 'http://localhost:3000'
 	}
}
```
# my package.json scripts

```
"scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "NODE_ENV=production nuxtent generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  }
```

So When I run `npm run generate`. Why OPEN http://localhost:3000 ?

```
> cuckoo@1.0.0 generate /home/wi/bin/wi-cuckoo.gitpage
> NODE_ENV=production nuxtent generate

  nuxt:generate Generating... +0ms
[AXIOS] Base URL: http://wi-cuckoo.io/content-api , Browser: http://wi-cuckoo.io/_nuxt/content

 OPEN  http://localhost:3000

  nuxt:build App root: /home/wi/bin/wi-cuckoo.gitpage +0ms
```

**Comment by STnetwork** [comment]
try it like that : 

`"generate": "NODE_ENV='production' nuxtent generate",`

**Comment by wi-cuckoo** [comment]
@STnetwork Oh, that doesn't matter.  I tried `HOST=wi-cuckoo.io PORT=80 NODE_ENV=production nuxtent generate`   
although it can work, but should run as root to listen 80 port. No a good idea. Hope the developer can solve it

**Comment by STnetwork** [comment]
ok, it's strange because on the nuxtent-template, the behavior is different, there isn't `OPEN  http://localhost:3000`

**Comment by alidcastano** [comment]
What's the problem here exactly? 

The `OPEN  http://localhost:3000` part is the `@nuxtjs/axios` module which nuxtent configures so that the content can be easily fetched with the `app.$content` method.

You can change the url by configuring `api.baseURL`".

**Comment by wi-cuckoo** [comment]
@alidcastano There is a bug in nuxtent when generate static files. In my config above, the *.json file requests in static page will go to http://localhost:3000. Maybe you could try generating static files by yourself and see what happened. If there is extra config to solve this bug, please update the doc. No any message in the [project doc](https://nuxtent.now.sh/guide/configuration).

**Comment by alidcastano** [comment]
Hey @wi-cuckoo I coincidently stumbled upon this problem today too #56. I will make a fix for this soon. Thanks for opening up the issue

**Comment by wi-cuckoo** [comment]
@alidcastano  Okay. It's not a problem to **OPEN http://localhost:3000**. The problem is if I set don't set NODE_NEV = production. The request of some file in generated static files will be on localhost:3000. Absolutely that's incorrect, it should be the domain of production.

**Comment by STnetwork** [comment]
I had the same problem, even if you remove `NODE_NEV = production`, when you want `nuxtent generate`, it uses `http://localhost:3000` the `[AXIOS] Base URL`, so how it would be possible de put a domain instead the localhost:3000 ?

**Comment by wi-cuckoo** [comment]
@alidcastano There is still many problems. I suggest that you could build a demo with nuxt+nuxtent. and generate static files, then deloy it on github as git page. You'll understand what we encountered. If the road is OK, you can post it to our users to help solving.

**Comment by alidcastano** [comment]
@STnetwork so the site builds, correct? are you experiencing problems when you deploy the site and try to fetch the content? I'll be fixing this either today or tomorrow so please let me know and be as specific as possible with the problem you are experiencing. And thanks again for using Nuxtent and helping get to the bottom of the early problems

**Comment by wi-cuckoo** [comment]
@alidcastano  Thanks for you reply. May the former problems caused by the lack of document or my incorrect config. Now, I just encounter the problem #56 and #57. And maybe the #57 and #59 is just one problem. I encounter these both is generation.   
**The last, I hope the final correct example of how to deploy on GitHub**

**Comment by STnetwork** [comment]
Why when you generate without `NODE_ENV='production'`, it used the basic url axios to have access to the `content-api` like you said, and no the localhost:3000 automatically ?

Because when I generate with this nuxent.config : 

```
const hljs = require('highlight.js')

module.exports = {
// content/HelloWorld.md --> posts/hello-world
 content: {
   page: '/_slug',
   permalink: ":slug",
    generate: [ // for static build
      'get', 'getAll'
    ],
   isPost: false
 },

  parsers: {
    md: {
      highlight: (code, lang) => {
        if (!(lang && hljs.getLanguage(lang))) return ''
        return hljs.highlight(lang, code, true).value
      }
    }
  },
	
  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://mydomain.com'
      : 'http://myipvps:3000'
  }
}
```

It cannot access to my BaseUrl for generate with the api-content

**Comment by STnetwork** [comment]
@alidcastano
Another thing you should see is when we re-actualize or go to a page static directly on a mardown file, it doesn't display the page it appears `undefined`.

You can see an example here : https://stnetworkbis.surge.sh/hello-world/

**Comment by STnetwork** [comment]
@alidcastano
Did you find a solution about why it connects to the `BaseUrl` to access to the `content-api` during the generating instead of something we can put in the `package.json` like `"HOST=0.0.0.0 PORT=3000 IS_STATIC=true nuxtent generate"` ?

**Comment by STnetwork** [comment]
I found a temporary fix in the `module.js` of your module I changed : 

`browserBaseURL:a.baseURL+(process.env.STATIC?a.browserPrefix:a.serverPrefix)}])` by 
`browserBaseURL:(process.env.STATIC?a.browserPrefix:a.serverPrefix)}])`

**Comment by suhogrozdje** [comment]
I am also experiencing the same issue, BarryPH's hacky solution did the trick, but it indeed is hacky.

To make the issue clear in a few words: when running `nuxtent generate`, axios baseURL is set (by default) to `http://localhost:3000/`, which is good, but the problem emerges when one loads generated content in the browser: there, axios baseURL is still set to `http://localhost:3000` instead of e.g. `https://nuxtent.now.sh` even if you set `baseURL: process.env.NODE_ENV === 'production' ? 'http://localhost:3000' : 'https://nuxtent.now.sh'` nuxtent.config.js. This should not be so, because the generated content gets served on `https://nuxtent.now.sh` where `localhost:3000` is not accessible, obviously.

May I ask why the baseURL is absolute? It seems to me that this problem wouldn't be present if you just left baseURL empty, making the whole path relative. I may be wrong bout that.

**Comment by suhogrozdje** [comment]
For me, it works (as predicted) if I put this into nuxtent.config.js:
```
module.exports = {
  ...
  api: {
    baseURL: ''
  }
}
```

**Comment by STnetwork** [comment]
@suhogrozdje 

Thanks for this solution it works well for me, I felt alone with this problem !

**Comment by suhogrozdje** [comment]
It works with Github Pages for me. But there are other problems I am experiencing, such as when i navigate directly to a post (i.e. refreshing when on it) and then navigating away from it, the content doesn't change. When I try then to refresh, it works again, but when I try to go back, it emits an error:

```
GET http://localhost:3000/_nuxt/content/articles/mathematics.whats-this-about..json 404 (Not Found)
```

This plugin seems to be a bit laggy. I think those of us who feel up to the task should contribute to it by debugging their errors and making a pull request, as there seems to be too much work for the author, which is understandable.

**Comment by alidcastano** [comment]
So sorry for being unresponsive! Thanks for finding a solution @suhogrozdje. PR merged!

**Comment by influx-agence** [comment]
[re up ?](https://github.com/nuxt/nuxt.js/issues/3881#issuecomment-422206760)
