### ISSUE TITLE
nginx proxy server "/content-api/hello-world" "Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by STnetwork** [nuxt-community/nuxtent-module#54]
I have a very strange behavior, I successed to configure my proxy nginx, the main page is ok https://mydomain. 
Also when I go to https://mydomain/hello-world, but only directly, when I click on `See Your First Post` for go to https://mydomain/hello-world, I have `500 Network Error`.

![image](https://user-images.githubusercontent.com/26366663/29833346-67955060-8ceb-11e7-9a2d-61784b755d70.png)

In developper tools I have this message : 

`XMLHttpRequest cannot load http://myipvps:3000/content-api/hello-world?. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mydomain.fr' is therefore not allowed access.`

Where can I add the `Access-Control-Allow-Origin` on the API nuxtent ?

edit: when I click on `See Your First Post`  by open a new tab, it's working.

**Comment by alidcastano** [comment]
What's your nuxtent configuration look like? 

You need to set `api.baseURL` appropriately for production build.

**Comment by STnetwork** [comment]
I have this

```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://myipvps:3000'
      : 'http://myipvps:3000'
  }
}
```

**Comment by alidcastano** [comment]
yes because you set the base url to be your production url for development. 


```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://localhost:3000'
      : 'http://myipvps:3000'
  }
}

```

**Comment by STnetwork** [comment]
Your solution doesn't work, I remind you that I'am behind a proxy nginx server with a mydomain.com and myipvps:3000 for the npm.

 I no longer have the message about `Access-Control-Allow-Origin` like that : 

my `nuxtent.config.js`
```
module.exports = {
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://mydomain.com'
      : 'http://myipvps:3000'
  }
}
```

and my `package.json`
```
  "scripts": {
    "dev": "HOST=myipvps PORT=3000 nuxt",
    "build": "NODE_ENV='production' HOST=myipvps PORT=3000 nuxt build",
    "start": "NODE_ENV='production' HOST=myipvps PORT=3000 nuxt start",
    "generate": "NODE_ENV='production' IS_STATIC=true nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "deploy": "push-dir --dir=dist --branch=gh-pages --cleanup",
    "precommit": "npm run lint"
  },
```

Now the transition since `mydomain.com` to ---> `mydomain.com/hello-world` works well.
But when I want to access directly to `mydomain.com/hello-world` in dev console I have `403 (NuxtServerError)`
and in the browser page : 

![image](https://user-images.githubusercontent.com/26366663/29882573-bf2cd3da-8dad-11e7-91eb-21cb4c593c17.png)

**Comment by alidcastano** [comment]
This is likely related to #43. 

Add `isStatic: true` to your configuration. Let me know if that works. Otherwise, I'll need more information about the error reported in your browser's console.

```
module.exports = {
  isStatic: true,
  content: {
    permalink: ':slug',
    page: '/_content',
    isPost: false
  },

  api: {
    baseURL: process.env.NODE_ENV === 'production'
      ? 'http://mydomain.com'
      : 'http://myipvps:3000'
  }
}
```

**Comment by STnetwork** [comment]
with `isStatic: true`, it's worse.

by `mydomain.com`, the main page works, but not the transition between `mydomain.com` to `mydomain.com/hello-world`, even directly to `mydomain.com/hello-world` .

in the devconsole I have this message 
```
GET http://mydomain.com/content-api/hello-world.json 404 (Not Found)
(anonymous) @ xhr.js:178
t.exports @ xhr.js:12
t.exports @ dispatchRequest.js:50
Promise resolved (async)
XmWM.r.request @ Axios.js:58
r.(anonymous function) @ Axios.js:68
(anonymous) @ bind.js:9
(anonymous) @ dist.plugin.375e22d5.js:51
r @ runtime.js:65
(anonymous) @ runtime.js:303
t.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ dist.plugin.375e22d5.js:32
(anonymous) @ dist.plugin.375e22d5.js:69
r @ runtime.js:65
(anonymous) @ runtime.js:303
t.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
r @ dist.plugin.375e22d5.js:62
(anonymous) @ _content.e965ea5a22699d4e4c56.js:82
r @ runtime.js:65
(anonymous) @ runtime.js:303
t.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
t @ _content.e965ea5a22699d4e4c56.js:109
f @ utils.js:138
(anonymous) @ client.js:271
(anonymous) @ client.js:256
r @ runtime.js:65
(anonymous) @ runtime.js:303
t.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
r @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
r @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
r @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ app.2b0bca8ee37fc1320663.js:2740
h @ vue-router.esm.js:1870
r @ vue-router.esm.js:1652
(anonymous) @ vue-router.esm.js:1653
(anonymous) @ vue-router.esm.js:1891
(anonymous) @ client.js:102
r @ runtime.js:65
(anonymous) @ runtime.js:303
t.(anonymous function) @ runtime.js:117
r @ asyncToGenerator.js:17
(anonymous) @ asyncToGenerator.js:28
Promise resolved (async)
r @ asyncToGenerator.js:27
(anonymous) @ asyncToGenerator.js:35
e @ _export.js:35
(anonymous) @ asyncToGenerator.js:14
(anonymous) @ app.2b0bca8ee37fc1320663.js:2488
h @ vue-router.esm.js:1870
r @ vue-router.esm.js:1652
r @ vue-router.esm.js:1656
at @ vue-router.esm.js:1660
te.confirmTransition @ vue-router.esm.js:1899
te.transitionTo @ vue-router.esm.js:1801
e.push @ vue-router.esm.js:2099
oe.push @ vue-router.esm.js:2416
w @ vue-router.esm.js:404
e @ vue.runtime.esm.js:1733`
```

for informtation when I try to access `http://mydomain.com/content-api/` it works, it displays : 

```
[{"title":"Hello World","meta":{"index":0,"fileName":"HelloWorld.comp.md","section":"/","dirName":"/","filePath":"/home/nginx/domains/mydomain.com/public/mydomain/content/HelloWorld.comp.md"},"date":"08-30-2017","path":"/hello-world","permalink":"/hello-world","anchors":[],"body":{"relativePath":"./HelloWorld.comp.md"}}]
```

**Comment by STnetwork** [comment]
Ok i found, it was my proxy cloudflare dns who did that, I disabled the HTTP proxy cloudfare on my domain, and now it works, sorry for the inconvenience !

**Comment by alidcastano** [comment]
Glad you figured it out. Btw if it's not a static version of side you can disregard `isStatic` comment.

**Comment by STnetwork** [comment]
yes, just for information you intend in future to do the nuxtent module work in complete static ?

**Comment by alidcastano** [comment]
The only aspect that doesn't work is markdown components (and some methods such as `geBetween` which were only intended application builds). At sometime when 1.0 is officially released I will fix that.

**Comment by STnetwork** [comment]
Ok, I hope you will do that quickly because the main reason to use nuxtent for me is to make static markdown components :), so for the moment I create my website with your module without static and then I will do when you'll fix all. Good luck !
