### ISSUE TITLE
Error when having nuxt `srcDir` option set

### ISSUE THREAD

**Issue by medfreeman** [nuxt-community/nuxtent-module#55]
I have a site with nuxt `srcDir` option set to `/src`.
Running `npm run dev` or `yarn dev` yields:
```
 ERROR  Failed to compile with 1 errors                                 14:38:06

This relative module was not found:

* ../content in ./.nuxt/dist.plugin.8704b2f2.js
```

The culprit is here: https://github.com/nuxt-community/nuxtent-module/blob/5f64b681a7f180822acfe7178b3859364264604b/lib/module.js#L114

I'll send a PR later with support for `srcDir` option .
For now i can make webpack shut up by having a second, empty `content` dir at the root of my app, but i suppose i won't be able to use vue components in markdown.

**Comment by alidcastano** [comment]
Haha.. yeah I've been meaning to get this working (hence the `TODO`) as that is how I wanted my site setup, with a `/content` and a  `/src` directory. A PR would be great. 

And yeah, one problem you'll encounter with changing the directory setup is that it causes problems with markdown components. I'm not sure if the latest Nuxt versions make this easier to fix. I haven't had time to look into it. But an alternative would be to have a separate directory inside `/src` for markdown components and manually import them yourself.

**Comment by medfreeman** [comment]
You probably just have to use `join('~/', srcDir)`, since it is aliased in nuxt webpack config.
I have to go for a few hours, but i'll test this when back and submit the PR.
