### ISSUE TITLE
app.$content is not a function in hmr during nuxtent generate 

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#57]

**Comment by wi-cuckoo** [comment]
Oops, I just encounter the problem. How to solve

**Comment by alidcastano** [comment]
Temporary fix: close any open windows before you run `nuxtent generate`

**Comment by wi-cuckoo** [comment]
@alidcastano What any windows means, in broswer?

**Comment by alidcastano** [comment]
Yes, any open windows or tabs
