### ISSUE TITLE
isPost and dates

### ISSUE THREAD

**Issue by lclaytont** [nuxt-community/nuxtent-module#62]
In the documentation it states that isPost defaults to true. However it is unclear how to work with dates with nuxtent. 

For example, I am trying to build a blog and sort posts by date. When I use {{ post.date }} in my template, all my posts have the same date. If I statically put date into the metadata of the markdown files I have do some wonkey computed value thing to order my posts. I don't mind doing that, but I am curious how any one else has used dates with nuxtent and if anyone cares to expound on the appropriate way to do this.

**Comment by alidcastano** [comment]
{{ post.date }} grabs the date used in your file name, e.g. `2017-08-01-MyPost.vue` would grab `2017-08-01` as the date.

Dated post are sorted by newest-oldest by default.

But yes you can sort them inside vue components. For example: 

```
async asyncData({ app }) {
  return {
    posts: (await app.$content('/').getAll()).sort((page1, page2) => page2.date - page1.date)
  }
}
```

**Comment by joostdecock** [comment]
Feel free to copy this: https://github.com/joostdecock/nuxtdown-module/blob/master/README.md#ispost
