### ISSUE TITLE
multiple content types - help need

### ISSUE THREAD

**Issue by STnetwork** [nuxt-community/nuxtent-module#63]
Hi,

Is it posssible to add another folder into a folder in the content ? for example I would like something like this : 

![2017_09_10_14_45_11_c_users_stnetwork_ atom_atom](https://user-images.githubusercontent.com/26366663/30249182-d6caa4cc-9636-11e7-85ff-4a1c69101242.png)

You can see the that in my repo maybe you will understand better : 

[STnetwork.fr](https://github.com/STnetwork/stnetwork.fr)

I can not access to /linux/centos or /linux/debian, I think I have a probleme in my nuxtent.config : 

```
module.exports = {
  content: [
    ['home', {
      page: '/home/slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
    ['linux', {
      page: '/linux/slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
    ['linux/centos', {
      page: '/linux/centos/_slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
    ['linux/debian', {
      page: '/linux/debian/slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
    ['windows', {
      page: '/windows/slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
    ['network', {
      page: '/network/slug',
      permalink: "/:slug",
      isPost: false,
      generate: ['get', 'getAll']
    }],
  ],
```

**Comment by alidcastano** [comment]
Hi @STnetwork 

You only need one configuration for the top level linux directory (remove `linux/debian` etc.) Then you can organize each of the sub folders inside components via the `page.meta.section` property. 

Here's an example of how I did it in the Ency documentation: https://github.com/encyjs/docs/blob/master/components/GuideToolbar.vue

**Comment by STnetwork** [comment]
Thanks, to be honest, I don't know how to do that exactely.

In my `linux.vue` is it good like that ?

```
<template>
  <section class="container">
     <ul>
       <li v-for="project in linux">
        <nuxt-link :to="'/linux' + linux.permalink">{{  linux.name }}</nuxt-link>
      </li>
    </ul>
    <nuxt-child />
  </section>
</template>

<script>
export default {
  async asyncData ({ app }) {
    return {
      projects: await app.$content('/linux').getAll()
    }
  }
}

function organizeSections (pages) {
  const menu = { centos: [], debian: [] }
  pages.forEach(page => {  // organize
    const pageSection = page.meta.section.replace('/', '')
    if (menu[pageSection]) menu[pageSection].push(page)
  })
  Object.keys(menu).forEach(key => {  // order
    menu[key].sort((p1, p2) => p1.order - p2.order)
  })
  return menu
}
</script>
```

**Comment by STnetwork** [comment]
@alidcastano 

could you help me please ?

**Comment by alidcastano** [comment]
@STnetwork Sorry for the delay. What is your question exactly? 

From your code, you also need to store the organized pages via computed properties so that you can use them in the template: 

```
computed: {
    linux() {
      return organizeSections(this.projects) 
   }
}
```

**Comment by alidcastano** [comment]
hi @STnetwork just realized the `path` property was using outdated API and was not working properly. This might have caused problems if you were using ency repo as an example. But now has been updated and will be released in next version.
