### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by pnSauces2017** [nuxt-community/nuxtent-module#68]
I am trying to deploy my nuxt project via github pages. All works well except that when I go to the blog portion of my site, which I am using nuxtent for, I get a mixed content error. At the moment I am not using a custom domain and gh pages defaults to SSL, which is great. But my blog posts a 500 error saying that I am making a http request to content-api. This content has already been generated of course though. Any ideas on why it doesn't just serve the static versions of these pages and instead tries to connect to the content-api?

**Comment by pnSauces2017** [comment]
Here is the specific error I get in the console when I try to navigate to the blog page:

```xhr.js:178 Mixed Content: The page at 'https://pnsauces2017.github.io/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/_nuxt/content/_all.json'. This request has been blocked; the content must be served over HTTPS.```

**Comment by pnSauces2017** [comment]
Solution from #53 fixes it. If you generate your files for a static site make sure your api.baseURL is set to an empty string.

**Comment by alidcastano** [comment]
Ok, thanks for the update. I just merged @suhogrozdje's fix and an empty string for baseURL will be the default in the next version of Nuxtent.
