### ISSUE TITLE
Allow `.yml` content files

### ISSUE THREAD

**Issue by medfreeman** [nuxt-community/nuxtent-module#69]
Atm this module only reads `.md` and `.yaml` files and does not support `.yml files`.
https://github.com/nuxt-community/nuxtent-module/blob/da574f5ceab9a8e8fad81389a977ff385045889e/lib/content/page.js#L108
https://github.com/nuxt-community/nuxtent-module/blob/da574f5ceab9a8e8fad81389a977ff385045889e/lib/content/page.js#L138

**Comment by alidcastano** [comment]
Sure, feel free to add this
