### ISSUE TITLE
NuxtServerError after upgrading to latest Nuxt rc

### ISSUE THREAD

**Issue by turnavies** [nuxt-community/nuxtent-module#71]
On a Mac — Sierra 10.12.6 (16G29)
```
$ node -v
v6.11.2
$ npm -v
3.10.10
```

Following quickstart instructions:
```
$ vue init nuxt-community/nuxtent-template my-site
$ cd my-site
$ yarn
```

and subsequently upgrading to latest Nuxt (1.0.0-rc11)
```
$ yarn add nuxt@1.0.0-rc11
```

After succesful install, running `npm run dev`,
navigating through http://localhost:3000 to http://localhost:3000/hello-world works, but doesn't show any of the Markdown content in HelloWorld.comp.md. 

On refresh of http://localhost:3000/hello-world, I get a 500 NuxtServerError
```
NuxtServerError
render function or template not defined in component: anonymous
```

Server console doesn't show any error. 

Thoughts?

**Comment by turnavies** [comment]
Seems broken from `nuxt@1.0.0-rc3`

**Comment by darisi** [comment]
same problem here with rc11, couldn't figure it out yet.

**Comment by alidcastano** [comment]
Yes, this is related to #34; the error is in regards to markdown components. Going to look into this now
