### ISSUE TITLE
Restore / Create end-to-end tests

### ISSUE THREAD

**Issue by medfreeman** [nuxt-community/nuxtent-module#72]
Hi, i've started to standardize this module to help develop it in the future, and guarantee its stability.
Starting by restoring e2e tests.
I hope you'll find this useful.

**Comment by medfreeman** [comment]
`npm run e2e`

**Comment by medfreeman** [comment]
The next contributions are [here](https://github.com/medfreeman/nuxtent-module/compare/tests...medfreeman:standard-js?expand=1).

**Comment by alidcastano** [comment]
I've unfortunately haven't had enough time to work on Nuxtent so that's great news. I'll review these changes by today. Thanks for contributing.

I've been trying to find time to resolve some of these issues, so let me know what changes you're working on so that we don't repeat the work.
