### ISSUE TITLE
example multiple-content-types not work with 404 error

### ISSUE THREAD

**Issue by alterhu2020** [nuxt-community/nuxtent-module#83]
##  Environment 
OS Version: Windows 7 Enterprise SP1
NodeJS: 8.5.0
NPM: 5.4.2
Nuxt: latest
Nuxtent-module: latest (1.0.0)

Hi team,
It's too sad that I had to say that the example in you official repository still not work for you current latest release version.

## Steps to reproduce
1. Download the example code:  [https://github.com/nuxt-community/nuxtent-module/tree/master/examples/multiple-content-types](https://github.com/nuxt-community/nuxtent-module/tree/master/examples/multiple-content-types)
2. Try command `npm install`
3. Try command `npm run dev`
4. Open the browser url: http://localhost:3000
5. Click the link `See all my posts`
## Actual Result
1. When navigate to the root url :http://localhost:3000, it will show below exception:
```
[Vue warn]: Method "$delete" conflicts with an existing Vue instance method. Avo
id defining component methods that start with _ or $.
```
![image](https://user-images.githubusercontent.com/5029046/30850335-0145cb6c-a25a-11e7-93c4-ea30fba2b8ea.png)

2. When click the link 'See all my posts', it will totally go to 404 page.
```
GET http://localhost:3000/content-api/posts/? 404 (Not Found)
```
![image](https://user-images.githubusercontent.com/5029046/30850393-42b15530-a25a-11e7-8ece-575b850894c1.png)

I think it caused by incorrect axios's baseURL setting. could you try it in your side?
thanks.

**Comment by alterhu2020** [comment]
Hi team,
 I found the Vue warning had lasted for a long time, but you all had not noticed this .

**Comment by medfreeman** [comment]
Thanks for reporting this!
It is again a specific windows error.

@alidcastano can you add the project to [Appveyor](https://www.appveyor.com/) so we can have tested windows builds ?
Thanks

**Comment by STnetwork** [comment]
@medfreeman I had the same error on CentOS, I don't think it's specific to WIndows.

**Comment by medfreeman** [comment]
@STnetwork thanks, i mixed up different testing sessions, and i encountered the same one while running the example.
I wonder what specific difference produces these warnings.

**Comment by alterhu2020** [comment]
@medfreeman , any update for this critical issue , It totally not worked for nuxtent project.

**Comment by medfreeman** [comment]
@alterhu2020 the warnings have now disappeared with the latest commit, they were related to an old `@nuxtjs/axios` version. I have now updated the module from ^2.2.1 to ^4.3.0 in all examples.

Concerning your error, can you try with the updated examples ?

If it doesn't resolve your problem,
can you tell me if your 'See all my posts' link points to "http://localhost:3000/content-api/posts/?" ?
What is your `baseUrl` setting ?

**Comment by STnetwork** [comment]
@medfreeman for me it's resolved.
You should see the process generate, is it normal to have `(Browser: /content-api)` during the generate process whereas before it was `(Browser: /_nuxt/content)`

![image](https://user-images.githubusercontent.com/26366663/30917370-21788936-a39c-11e7-9a89-47e86cdbbeae.png)

At the end he doesn't generate all files in the multiple-content example.

**Comment by alterhu2020** [comment]
Hi @medfreeman , yes when use the latest `@nuxtjs/axios` ,the $delete warning had not showed again ,bbut the 404 page is still showing for this example.
The reproduce steps just as this issue's description.
see the error screenshot for this.
![image](https://user-images.githubusercontent.com/5029046/30922530-ff9c85f2-a3db-11e7-8fa8-f37b02c7b399.png)

**Comment by STnetwork** [comment]
@alterhu2020 @medfreeman 
It's probably specific to your env or windows, because I don't have this message on CentOS at all.

**Comment by alidcastano** [comment]
Why are you visiting `content-api/posts/?`

What does `content-api/posts` show?

**Comment by alidcastano** [comment]
@STnetwork Thanks for looking into this. It works for me as well so this most be an env specific issue. But I did experience two other issues #88 #89 so we will work to fix them. 

Thanks for being patient as we work out the kinks, and a special shoutout to @medfreeman for the great PRS.

**Comment by AlokJoshi** [comment]
@medfreeman I am fairly new to this but I get hundreds of warnings:
[Vue warn]: Method "$delete" conflicts with an existing Vue instance method. Avo
id defining component methods that start with _ or $.
Can you please let me know what may be causing this.? 
I am using Windows 7 and I installed the latest nuxt by changing the package.json entry to :"latest" and running npm install. (I think it installed rc11 but I cannot get back to that screen and I don't know how to find out the nuxt version installed)
