### ISSUE TITLE
nuxt generate only causes 404

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#89]
@medfreeman I'm still getting 404 when I run nuxt generate (instead of nuxtent generate with previous binaries)

JSON files are generated but it seems like pages are not compiled appropriately. For example with multiple content type example I get: 

```
==== Error report ==== 
Route: '/nuxtent' thrown an error: 
{"statusCode":404,"message":"This page could not be found"}

Route: '/ency' thrown an error: 
{"statusCode":404,"message":"This page could not be found"}
```
If I serve the site, the client navigation works fine but refreshing page displays `not found` error.

Also related to #88, if we stick to not having binaries we have to let users specify `static=true` some other way, e.g. via config, so that browser URL can be set appropriately and static files can be generated.

**Comment by alidcastano** [comment]
I feel like your solution (https://github.com/nuxt-community/nuxtent-module/blob/master/lib/module.js#L131) should be equivalent to using binaries, as the only special thing I was doing was starting the Nuxt server so that server middleware could be active when pages were being generated.

**Comment by STnetwork** [comment]
If it can help you I have a small different error when a set an `apiBaseUrl`

![image](https://user-images.githubusercontent.com/26366663/30927549-11fb6e02-a3b9-11e7-87ef-70744c7eaacb.png)


my 

> nuxtent.config.js 

```
module.exports = {
  content: [
    [
      'posts',
      {
        page: '/_post',
        permalink: ':year/:slug',
        generate: ['get', 'getAll']
      }
    ],
    [
      'projects',
      {
        page: '/projects/slug',
        permalink: '/:slug',
        isPost: false,
        generate: ['get', 'getAll']
      }
    ]
  ],

api: {
  baseURL: process.env.NODE_ENV === 'production'
    ? 'http://stnetwork.surge.sh'
    : 'http://localhost:3000'
}
}
```

my 

> package.json 


{
  "name": "example",
  "version": "1.0.0",
  "description": "nuxtent multiple content types example",
  "author": "Alid Castano <alidcastano@gmail.com>",
  "dependencies": {
    "@nuxtjs/axios": "^4.3.0",
    "nuxt": "latest",
    "nuxtent": "latest"
  },
  "scripts": {
    "dev": "HOST=0.0.0.0 PORT=3000 nuxt",
    "build": "nuxt build",
    "start": "HOST=0.0.0.0 PORT=3000 nuxt start",
    "generate": "STATIC=true NODE_ENV='production' nuxt generate",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "precommit": "npm run lint"
  },
  "devDependencies": {
    "@nuxtjs/cssnano": "^1.0.1",
    "@nuxtjs/optimize": "^1.1.1",
    "@nuxtjs/pwa": "^0.2.1",
    "babel-eslint": "^8.0.1",
    "buefy": "^0.5.2",
    "bulmaswatch": "^0.5.0",
    "eslint": "^4.7.2",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.2.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1",
    "highlight.js": "^9.12.0",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6"
  }
}

**Comment by STnetwork** [comment]
@alidcastano @medfreeman 

Sorry but I updated nuxtent with the version 1.0.2 and I always have exactly the same error that I posted in my screen above.
