### ISSUE TITLE
update documentation 

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/nuxtent-module#90]
Off the top of my head: 
- Add` isStatic` option to configuration section 
- Add `baseURL` explanation for dynamic and static sites ( can leave baseURl empty on static build)
- Add brief explanation for how to deploy site via nuxt commands
- Improve automatic navigation section
- Add markdown component slots when it is released (see #85)

@medfreeman am I missing any changes that we should document?

**Comment by medfreeman** [comment]
@alidcastano i'll answer tomorrow, too tired sorry.
- `isStatic` doesn't exist anymore, `generate` is automatically detected
