### ISSUE TITLE
Compilation fail on windows

### ISSUE THREAD

**Issue by yoanmarchal** [nuxt-community/nuxtent-module#94]
I try nuxtent on windows, it fail ,so i lookup with mac os 

1. mac os X 10.11.6
- node 8.5.0
- npm 5.4.2 
i can run
`vue init nuxt-community/nuxtent-template my-site` 
no probs here

2. Windows 10
- node 8.6.0
- npm 5.3.0
i still got  error on compilation

> Module build failed: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of null
at getSection (D:\projects\nuxt\my-site\node_modules\nuxtent\dist\loader.js:19:33)
at Object.module.exports (D:\projects\nuxt\my-site\node_modules\nuxtent\dist\loader.js:114:19)

**Comment by medfreeman** [comment]
thanks for your report! i am aware of this issue, and plan to avoid this in the future by having automated windows builds with [AppVeyor](https://www.appveyor.com/).
We're waiting for proper access atm.
When the others important issues are fixed, i'll switch to my windows instance to resolve this.

**Comment by alidcastano** [comment]
Luckily I got a Windows computer recently so I was able to fix the bumps and get Nuxtent running :) Should be working by next release 👍
