### ISSUE TITLE
Date format of posts and pages is different

### ISSUE THREAD

**Issue by CHH** [nuxt-community/nuxtent-module#98]
The format of a content type with `isPost: true` follows ISO8601. The date that was determined by the file's ctime, when the content type is not a post, doesn't follow the same format, but dd-mm-YYYY instead.

Relevant line:

https://github.com/nuxt-community/nuxtent-module/blob/56e04d7886dbc8fe39c5fb8c0e48a415b5f960d0/lib/content/page.js#L168

Is this by design, or a bug?

**Comment by alidcastano** [comment]
Yea that's an oversight, they should follow the same format - YYYY-MM-DD
